defaults:
  timeout: 15
example_catalog1:
  catalog:
    verify: false
  sources:
    proxies:
      http: http://example.proxy.com:3000
      https: https://example.proxy.com:4000
    verify: false
    timeout: 30
example_catalog2:
  catalog:
    timeout: 10
    verify: false