defaults:
  try_timeout: 15
  tries: 4
example_catalog1:
  catalog:
    verify: false
    tries: 5
  sources:
    proxies:
      http: http://example.proxy.com:3000
      https: https://example.proxy.com:4000
    verify: false
    try_timeout: 30
example_catalog2:
  catalog:
    try_timeout: 10
    verify: false