--- 
mailer: 
  password: bar
  port: 587
  smtp_server: smtp.example.com
  ssl: false
  user: foo
extraccion: 
  example_catalog1: 
    destinatarios: 
      - john@example.com
      - jane@example.com
  example_catalog2: 
    destinatarios: 
      - john@example.com
      - jane@example.com
scraping: 
  example_catalog1: 
    destinatarios: 
      - jane@example.com
  example_catalog2: 
    destinatarios: 
      - mike@example.com
