defensa:
  url: "http://datos.mindef.gov.ar/data.json"
  formato: "json"

salud:
  url: "http://datos.salud.gob.ar/data.json"
  formato: "json"

example_catalog1:
  url: "https://github.com/datosgobar/series-tiempo-ar-scraping/raw/master/samples/catalogs/example_catalog1.xlsx"
  formato: "xlsx"